### PR TITLE
CFP template

### PR DESCRIPTION
**Pull request by tormath1**
Well, this is basically a bare CFP template in order to be able to add talk proposals for the next meetups.
I also moved the previous meetup slides in a dedicated folder.

Feel free if you have other ideas for the template !

### CODE REVIEW

**Comment by pabluk** [comment]
Thanks @tormath1

**Comment by pabluk** [comment]
Reviewing PRs from a phone isn't the best experience :) @tormath1 I'm waiting for you to rebase and I'll merge it.

**Comment by tormath1** [comment]
I rebased, I can squash if you only want to merge one commit. :)

**Comment by pabluk** [comment]
It's perfect like this, thanks very much for your contribution @tormath1!

**Pull request merged**
